"use client";
import React from "react";
import "../css/style.css";
import { Montserrat } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Theme from "../theme-provider";
import AppProvider from "../app-provider";
import MainHeader from "@/components/common/header/mainHeader";
import MainFooter from "@/components/footer/mainFooter";
import { usePathname } from "next/navigation";
const inter = Montserrat({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// export const metadata = {
//   title: "Fizno Admin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentPath = usePathname();
  const hideSubheader =
    currentPath === "/seller/login" ||
    currentPath === "/seller/verification" ||
    currentPath === "/seller/forgot-password" ||
    currentPath === "/seller/register" ||
    currentPath === "/seller/sell" ||
    currentPath === "/seller/change-password";
  return (
    <html lang="en" suppressHydrationWarning>
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body
        className={`${inter.variable} font-inter antialiased bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400`}
      >
        <Theme>
          <AppProvider>
            {hideSubheader ? <MainHeader /> : null}
            {children}
            {hideSubheader ? <MainFooter /> : null}
          </AppProvider>
        </Theme>
      </body>
    </html>
  );
}
