"use client";
import "./css/style.css";
import { Montserrat } from "next/font/google";
import Theme from "./theme-provider";
import AppProvider from "./app-provider";
import Providers from "@/helpers/redux/providers";
import AuthProvider from "@/helpers/providers/authProvider";
import GlobalComponent from "@/components/globalComponent";
import GlobalProvider from "@/hoc/globalProvider";
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// export const metadata = {
//   title: "Fizno Admin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  guest,
}: {
  children: React.ReactNode;
  guest?: boolean;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        {/* Favicon Link */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="png" href="/favicon.png" sizes="any" />

        <title>Fizno Admin</title>
      </head>
      <body
        className={`${montserrat.variable} font-inter antialiased bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400`}
        style={{ fontFamily: montserrat.style.fontFamily }}
      >
        <Theme>
          <Providers>
            <GlobalComponent />
            <AuthProvider>
              <AppProvider>{children}</AppProvider>
              <GlobalProvider />
            </AuthProvider>
          </Providers>
        </Theme>
      </body>
    </html>
  );
}
